### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by JueXiuHuang** [JueXiuHuang/Text-Label-System#2]
- [ ] <功能> 標籤排序
- [ ] <功能> 斷詞與空格
- [ ] <漏洞> 標記多篇之後 Save 功能可能會出錯
- [ ] <功能> Save more message when meet error
- [x] <功能> 版本檢查
- [x] <功能> 右鍵標籤選取 'edit' 後才能修改標籤
- [x] <功能> Add language selector
- [x] <功能> Add tag abs_path to tag display
